const DB_KEY='ergofit_users_v1';
const SESSION_KEY='ergofit_user_session';
const API_CONFIG={enabled:false,url:''};
const logo='../assets/images/logo.svg';
const app=document.getElementById('user-app');
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function getUsers(){try{return JSON.parse(localStorage.getItem(DB_KEY))||[]}catch{return[]}}
function saveUsers(users){localStorage.setItem(DB_KEY,JSON.stringify(users))}
async function registerRemote(user){if(!API_CONFIG.enabled||!API_CONFIG.url)return false;const r=await fetch(API_CONFIG.url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(user)});if(!r.ok)throw new Error('No fue posible registrar el usuario');return true}
function logoMarkup(){return `<img class="logo" src="${logo}" alt="ERGOFIT">`}
function access(){app.innerHTML=`<div class="wrap"><div class="brand">${logoMarkup()}<h1>ERGOFIT</h1><p>Pausas activas · bienestar · movimiento</p></div><section class="card"><div class="tabs"><button class="active" data-tab="login">Ingresar</button><button data-tab="register">Registrarme</button></div><div id="access-form"></div><p class="note">Tu información se utiliza para personalizar el seguimiento de pausas activas. En producción, conecta ERGOFIT a un backend seguro antes de registrar datos personales.</p></section></div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showForm(b.dataset.tab));showForm('login')}
function showForm(tab){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const f=document.getElementById('access-form');if(tab==='login'){f.innerHTML=`<form id="login"><div class="field"><label>Correo electrónico</label><input name="email" type="email" autocomplete="email" required placeholder="nombre@empresa.com"></div><div class="field"><label>Contraseña</label><input name="password" type="password" autocomplete="current-password" required placeholder="••••••••"></div><button class="btn primary">Ingresar a ERGOFIT</button><div id="msg" class="status"></div></form>`;f.querySelector('form').onsubmit=login}else{f.innerHTML=`<form id="register"><div class="field"><label>Nombre completo</label><input name="name" autocomplete="name" required placeholder="Tu nombre"></div><div class="field"><label>Correo electrónico</label><input name="email" type="email" autocomplete="email" required placeholder="nombre@empresa.com"></div><div class="field"><label>Empresa / entidad</label><input name="company" autocomplete="organization" required placeholder="Empresa o entidad"></div><div class="field"><label>Área</label><input name="area" required placeholder="Ej. Talento Humano"></div><div class="field"><label>Contraseña</label><input name="password" type="password" minlength="8" autocomplete="new-password" required placeholder="Mínimo 8 caracteres"></div><button class="btn primary">Crear mi cuenta</button><div id="msg" class="status"></div></form>`;f.querySelector('form').onsubmit=register}}
async function register(e){e.preventDefault();const fd=new FormData(e.target),user={id:'u'+Date.now(),name:fd.get('name').trim(),email:fd.get('email').trim().toLowerCase(),company:fd.get('company').trim(),area:fd.get('area').trim(),password:fd.get('password'),createdAt:new Date().toISOString()};const users=getUsers();if(users.some(u=>u.email===user.email)){e.target.querySelector('#msg').textContent='Ese correo ya está registrado.';return}try{const remote=await registerRemote(user);if(!remote){users.push(user);saveUsers(users)}sessionStorage.setItem(SESSION_KEY,JSON.stringify(user));home(user)}catch(err){e.target.querySelector('#msg').textContent=err.message}}
function login(e){e.preventDefault();const fd=new FormData(e.target),email=fd.get('email').trim().toLowerCase(),password=fd.get('password'),u=getUsers().find(x=>x.email===email&&x.password===password);if(!u){e.target.querySelector('#msg').textContent='Credenciales no válidas.';return}sessionStorage.setItem(SESSION_KEY,JSON.stringify(u));home(u)}
function home(u){app.innerHTML=`<div class="wrap"><div class="brand">${logoMarkup()}<h1>ERGOFIT</h1><p>Tu espacio de bienestar laboral</p></div><div class="home"><section class="welcome"><h2>Hola, ${esc(u.name.split(' ')[0])} 👋</h2><p>Es momento de cuidar tu cuerpo durante la jornada.</p></section><div class="quick"><div class="tile"><span>Racha actual</span><strong>0 días</strong></div><div class="tile"><span>Pausas hoy</span><strong>0 / 3</strong></div></div><section class="exercise"><h3>🧘 Movilidad cervical</h3><p>5 minutos · Cuello y hombros</p><button class="btn primary" style="margin-top:14px">Iniciar pausa</button></section><section class="exercise"><h3>✋ Extensión de muñecas</h3><p>3 minutos · Antebrazos y muñecas</p><button class="btn primary" style="margin-top:14px">Iniciar pausa</button></section><button class="btn secondary logout" id="logout">Cerrar sesión</button></div></div>`;document.getElementById('logout').onclick=()=>{sessionStorage.removeItem(SESSION_KEY);access()}}
const existing=sessionStorage.getItem(SESSION_KEY);existing?home(JSON.parse(existing)):access();
